### ISSUE TITLE
Google Refresh token null

### ISSUE THREAD

**Issue by EldonMcGuinness** [EldonMcGuinness/UnraidCloudBackup#2]
For some reason the refresh tokens are not coming back with the google account setup. Will look into this.

**Comment by MMagTech** [comment]
Attepting to Setup Google Drive.  I've added the Google Drive API and creeated credentials.  Copied them in unRAID in the plugin and clicked Add Providor.  Was able to select my google login.  Screen is now hung on "oAuth2 Client
Please wait while we fetch your token!"  been hung for over 5  minutes.

**Comment by EldonMcGuinness** [comment]
This was caused by Google not issuing a refresh_token when the application has already been linked. To fix the issue, unlink the application from the google account and recreate the connection.
