### ISSUE TITLE
Stuck on, "Please wait while we fetch your token!"

### ISSUE THREAD

**Issue by MMagTech** [EldonMcGuinness/UnraidCloudBackup#3]
Attepting to Setup Google Drive. I've added the Google Drive API and creeated credentials. Copied them in unRAID in the plugin and clicked Add Providor. Was able to select my google login. Screen is now hung on "oAuth2 Client
Please wait while we fetch your token!" been hung for over 5 minutes.

**Comment by EldonMcGuinness** [comment]
This has been resolved, it was due to some debuging to figure out why google's oAuth was not working #2 

Please let me know if you continue to see this.

**Comment by MMagTech** [comment]
Authentication is now working.  Time to see if the sync works
