### ISSUE TITLE
Add input checking on cron input.

### ISSUE THREAD

**Issue by MMagTech** [EldonMcGuinness/UnraidCloudBackup#4]
Failed parsing crontab for user root.  Ive tried two differnent configs with no luck.  Could be user error.  Submitting in case it's not or someone else comes across this issue.  I'm syncing to Google Drive and have created the Template folder in Google Drive. Succesfully passed authentication and Google drive is added in the plugin as Existing Authentication. Tried the remote path as both /Templates/ and Template.

crond[1877]: failed parsing crontab for user root: ***** /usr/bin/rclone copy /boot/config/plugins/dockerMan/templates-user Google:/Templates/ --config /boot/config/plugins/CloudBackup/rclone.conf --drive-chunk-size 128M --log-file /var/log/CloudBackup.rclone.log --log-level INFO --stats 30s

crond[1877]: failed parsing crontab for user root: ***** /usr/bin/rclone copy /boot/config/plugins/dockerMan/templates-user/ Google:Templates --config /boot/config/plugins/CloudBackup/rclone.conf --drive-chunk-size 128M --log-file /var/log/CloudBackup.rclone.log --log-level INFO --stats 30s

**Comment by EldonMcGuinness** [comment]
Are you putting spaces between the *?

Should read `* * * * *` do keep in mind that means run every minute. 👍

**Comment by MMagTech** [comment]
Ah I may have omitted the spaces. Will reattempt in a few. Thanks for the heads up was just setting it to run every minute for testing purposes. Will end up setting it to weekly when all is working.

**Comment by MMagTech** [comment]
Still no luck. Corrected with spaces. However no failed parsing as previously recieving exit status now.   Tried /Template/ and Template still no files in Google Drive. Logs entries.

crond[1877]: exit status 1 from user root /usr/bin/rclone copy /boot/config/plugins/dockerMan/templates-user Google:/Templates/ --config /boot/config/plugins/CloudBackup/rclone.conf --drive-chunk-size 128M --log-file /var/log/CloudBackup.rclone.log --log-level INFO --stats 30s


crond[1877]: exit status 1 from user root /usr/bin/rclone copy /boot/config/plugins/dockerMan/templates-user/ Google:Templates --config /boot/config/plugins/CloudBackup/rclone.conf --drive-chunk-size 128M --log-file /var/log/CloudBackup.rclone.log --log-level INFO --stats 30s

**Comment by EldonMcGuinness** [comment]
Does the log file [ /var/log/CloudBackup.rclone.log ] show any clue?

**Comment by MMagTech** [comment]
Getting late here will take a look tomorrow

**Comment by MMagTech** [comment]
I've put about an hour into this and no luck.  I've even tried using the folder ID with no luck and numerous variations of the link to the Drive folder.  Have you been succesful at pushing to Google Drive?  If so can you possibly provide a sanatized screenshot of the Existing Tasks portion of the plugin.

**Comment by EldonMcGuinness** [comment]
Yes I have been able to get it working with Google, have it working right now. There is an oddity with Google though. Apparently, you can only have an app linked once and get the correct credentials returned. If you have previously linked it you will have to unlink it and link it again. Check this ticket for more information #6 

Can you post the logs of when the command runs?

**Comment by MMagTech** [comment]
Give build Build 2024.02.28-002 a try and all is working.  No changes from the first attempt I made using the folder name.  Here is a screenshot of my Existing Task in case anyone comes across this thread.

![Screenshot 2024-02-28 213956](https://github.com/EldonMcGuinness/UnraidCloudBackup/assets/64668236/db63a6b3-82ff-4c03-aedd-44fa121118f8)
